
# -- MODULES --
# Disabling a module disables the rest of that section.
# The sections are divided by the horizontal bars ( -------------- ).
Config_V: 2

# -----------------------------------------------------------------------------------------------------

# Crafting_Recipes adds 14 new recipes.
Crafting_Recipes: true

# -----------------------------------------------------------------------------------------------------

# Healing_And_Taming adds the ability to heal and tame dogs and cats with more
# type of food.
Healing_And_Taming: true

# You can set the probability percentage of an ocelot converting into a cat when
# they eat catnip from your hand. 0 - 100 %.
Ocelote_To_Cat_Percentage: 50

# -----------------------------------------------------------------------------------------------------

# Spiders_Enhanced modifies drops and habilities of spiders, making you to get
# more string from them.
Spiders_Enhanced: true

# You can set the probability percentage of an spider placing a web to trap a
# damaged player. 0 - 100 %.
Spiders_Generate_Web_Percentage: 25

# Sets the number of extra strings droped from spiders when they die. Randmonly
# from 0 to the value of your choice.
Spiders_Extra_String_Drop: 4

# -----------------------------------------------------------------------------------------------------

# Items_Renaming renames some items to make them more integrated with rest of
# the plugin.
Items_Renaming: true

# You can change the name of these modified items.
# Catnip is the plant that cats love. It overrides Pink Tulip Item name.
Catnip_Name: Catnip

# The new wool source: Fiber plant. It overrides Pink Azure Bluet Item name.
WoolPlant_Name: Fiber Plant

# The new wool armor, crafted with (fiber) wool.
Wool_Cap_Name: Wool Cap
Wool_Tunic_Name: Wool Tunic
Wool_Pants_Name: Wool Pants
Wool_Boots_Name: Wool Boots

# The new drink made of pumpkin seeds.
Pumpkin_Seed_Drink_Name: Pumpkin Seed Drink

# -----------------------------------------------------------------------------------------------------

# Mobs_Bleeding make pacific and passive mobs bleeding when they are atacked
Mobs_Bleeding: true

# -----------------------------------------------------------------------------------------------------

# Better_World modifica la generaci칩n del terreno para generar aleatoriamente:
# Fiber Plants en la hierba, cactus con flores de fibra en el desierto y Catnip en la jungla
Better_World: true

# Porcentaje de que un cactus que termina de crecer genere una flor de fibra
Cactus_Grow_Percentage: 50

# Permitir que el Wool Plant y el Cactus crezcan si le das Bone Meal
Allow_BoneMeal_On_WoolPlant_And_Cactus: true

# Si el mundo ya se gener칩 sin el plugin, habr치 escasez de Fiber Plants. Una alternativa es hacer que cuando un esqueleto spawnee, 
# genere Fiber Plants a su alrededor aleatoriamente.
# Por defecto esta propiedad est치 desactivada. Make sure que esta propiedad se activa de forma temporal para no saturar el mapa.
Skeletons_Generate_FiberPlants: false

# -----------------------------------------------------------------------------------------------------

# Buscar actualizaciones periodicamente y alertar de ellas en la consola
Find_Updates_Periodicly: true

# -----------------------------------------------------------------------------------------------------

# Show_Logo shows the logo in console on plugin loading.
Show_Logo: true
