Config_V: 2

# -- MODULES --
# Disabling a module disables the rest of that section.
# The sections are divided by the horizontal bars ( -------------- ).

# -----------------------------------------------------------------------------------------------------

# Crafting_Recipes adds 14 new recipes.
Crafting_Recipes: true

# -----------------------------------------------------------------------------------------------------

# Healing_And_Taming adds the ability to heal and tame dogs and cats with more
# type of food.
Healing_And_Taming: true

# You can set the probability percentage of an ocelot converting into a cat when
# they eat catnip from your hand. 0 - 100 %.
Ocelote_To_Cat_Percentage: 50

# -----------------------------------------------------------------------------------------------------

# Spiders_Enhanced modifies drops and habilities of spiders, making you to get
# more string from them.
Spiders_Enhanced: true

# You can set the probability percentage of an spider placing a web to trap a
# damaged player. 0 - 100 %.
Spiders_Generate_Web_Percentage: 25

# Sets the number of extra strings droped from spiders when they die. Randmonly
# from 0 to the value of your choice.
Spiders_Extra_String_Drop: 4

# -----------------------------------------------------------------------------------------------------

# Items_Renaming renames some items to make them more integrated with rest of
# the plugin.
Items_Renaming: true

# You can change the name of these modified items.
# Catnip is the plant that cats love. It overrides Pink Tulip Item name.
Catnip_Name: Catnip

# The new wool source: Fiber plant. It overrides Pink Azure Bluet Item name.
FiberPlant_Name: Fiber Plant

# The new wool armor, crafted with (fiber) wool.
Wool_Cap_Name: Wool Cap
Wool_Tunic_Name: Wool Tunic
Wool_Pants_Name: Wool Pants
Wool_Boots_Name: Wool Boots

# The new drink made of pumpkin seeds.
Pumpkin_Seed_Drink_Name: Pumpkin Seed Drink

# -----------------------------------------------------------------------------------------------------

# Mobs_Bleeding make pacific and passive mobs bleeding when they are atacked
Mobs_Bleeding: true

# -----------------------------------------------------------------------------------------------------

# Better_World modifies the generation of the terrain to generate randomly:
# Fiber Plants in the grass, Fiber Flowers in the cactus and Catnip in the jungle
Better_World: true

# If you want to generate extra fiber plants in the world
Generate_FiberPlant: true
# Number of fiber plants that will grow if bonemeal is applied. 0 disable the feature
BoneMeal_On_FiberPlant: 1

# If you want to generate extra catnip in the world
Generate_Catnip: true
# Number of catnip that will grow if bonemeal is applied. 0 disable the feature
BoneMeal_On_Catnip: 1

# Percentage of generating a fiber flower when a cactus finishes growing. 0 disables fiber flowers.
Generate_FiberFlower: 50
# Percentage that a cactus grows if bonemeal is applied 0 - 100%. 0 deactivates the growth of the cactus with bonemeal.
BoneMeal_On_Cactus: 50

# -----------------------------------------------------------------------------------------------------

# Check for updates periodically and alert them to the console
Find_Updates_Periodicly: true

# -----------------------------------------------------------------------------------------------------

# Show_Logo shows the logo in console on plugin loading.
Show_Logo: true


Allow_Metrics: true
